### ISSUE TITLE
add --fix-dry-run

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/Ethlint#170]
The `--fix-dry-run` option is exactly what it sounds like - it simply prints a report about what all fixes solium is going to apply instead of actually writing over files. This gives the user a **diff** between current code & what it would look like after applying the fixes.

**Comment by mushketyk** [comment]
Hey, @duaraghav8 I would like to implement this.
Does it mean that `applyFixes` should now return different output? Say something like:

```javascript
        return {
            fixesApplied: fixesApplied,
            // NEW OUTPUT FIELD
            diffsApplied: diffsApplied,
            fixedSourceCode: fixedSourceCode,
            remainingErrorMessages: remainingMessages
        };
```

**Comment by mushketyk** [comment]
@duaraghav8 On the other hand... Should Solium output applied diff in both `fix-dry-run` and `fix` modes?

**Comment by duaraghav8** [comment]
Hi @mushketyk, that's great to know!

1. When you pass code & config to `Solium.lintAndFix()`, it returns somethig like
```
{
        originalSourceCode: 'pragma solidity ^0.4.0;\n\n\nimport "./hello.sol";\n\ncontract Foo {\n\tstring hola = \'hello\';\n}\n',
        fixesApplied:[
                {
                        ruleName: 'quotes',
                        type: 'error',
                        node: [Object],
                        message: '\'hello\': String Literals must be quoted with double quotes only.',
                        line: 7,
                        column: 15,
                        fix: [Object]
                }
        ],
        fixedSourceCode: 'pragma solidity ^0.4.0;\n\n\nimport "./hello.sol";\n\ncontract Foo {\n\tstring hola = "hello";\n}\n',
        errorMessages: [
                {
                        type: 'warning',
                        message: '[DEPRECATED] Rule "double-quotes" is deprecated. Please use "quotes" instead.',
                        internal: true,
                        line: -1,
                        column: -1 },
                        { ruleName: 'double-quotes',
                        type: 'warning',
                        node: [Object],
                        message: '\'hello\': String Literals must be quoted with "double quotes" only.',
                        line: 7,
                        column: 15
                }
        ]
}
```

This result object gets passed to [cli.js](https://github.com/duaraghav8/Solium/blob/master/lib/cli.js). It is this **cli.js that actually writes to the target file** (see https://github.com/duaraghav8/Solium/blob/master/lib/cli.js#L93).

The solium library doesn't interact with the system in any way. So no, the `applyFixes`'s return object doesn't change.

Instead, we take the `fixesApplied` object from the result of lintAndFix (inside cli.js) and instead of actually writing to file, we just print the diff to stdout.

2. No, only `fix-dry-run` (in which case the user specifically asked for a diff). Showing diff even during `fix` will result in too much information being dumped on screen as codebases get larger. It kind of becomes overwhelming.

Hope I clearly explained things? Let me know if you have any questions

**Comment by mushketyk** [comment]
@duaraghav8 Everything seems clear now. I've created a PR.
