### ISSUE TITLE
Add option to dump stack trace (especially handy for Plugin developers)

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/Ethlint#171]
- What's the best (industry standard?) way of doing this? `--stack`? `--verbose`/`-v<Level>`?

**Comment by mushketyk** [comment]
@duaraghav8 `--verbose`/`-v` seems like a more flexible option.

**Comment by duaraghav8** [comment]
@mushketyk Yes. But I'm not very keen on also adding `-v` (because the uppercase `-V` is short for `--version`). It causes confusion.

Also, since this verbose info is aimed at developers (and not users), I also thought that `--dev` could be a suitable flag name. Because right now, its just stack traces. Eventually, verbose info will include all content being printed on screen that may be useful to anyone developing solium or something on top of it.

So with that in mind^, would you side toward `--dev` or `--verbose`?

**Comment by mushketyk** [comment]
@duaraghav8 It can also be `--debug` or `--stacktrace` as in Gradle CLI. I think `--debug` can be useful for developers, while the proposed `--verbose` flag may be used to output more information useful for users.

**Comment by duaraghav8** [comment]
You're right. `--debug` is the most suitable option for dumping stack traces (and other developer-friendly info).

**Comment by mushketyk** [comment]
@duaraghav8 `--debug` it is! To avoid merge conflicts, I can implement this once this PR is merged: https://github.com/duaraghav8/Solium/pull/186

**Comment by duaraghav8** [comment]
Great @mushketyk! Please go ahead and implement `--debug`, #186 is going to take some time before merging so I'll take care of conflicts.

It'll take time primarily because so far, everything in solium was being done synchronously and I'm planning to parallelise your version check code so it doesn't block the linting. I'll handle this so you need not worry about any conflicts.

**Comment by duaraghav8** [comment]
`--debug` option is already live by now, forgot to close this issue earlier.
Thanks for contributing!
