### ISSUE TITLE
security/enforce-explicit-visibility --fix defaulting to public seems dangerous

### ISSUE THREAD

**Issue by jashmenn** [duaraghav8/Ethlint#174]
I realize this is subjective, but if one runs `--fix` the `security/enforce-explicit-visibility` rule changes methods to `public` automatically. 

In my opinion it ought to default to `private` or not fix at all. Fixing automatically to `public` seems like a risky behavior in the case where it goes unnoticed.

**Comment by duaraghav8** [comment]
I fully agree with you, but I think you're slightly mis-interpreting the purpose of this rule.

It exists to only make sure that the developer has specified a visibility to a function. If none is specified, Solc will treat the function as `public` by default (see [docs](http://solidity.readthedocs.io/en/develop/contracts.html#visibility-and-getters)). So this rule merely puts `public` visibility to the function **so the developer sees what solc sees**. Had solc been treating functions as private by default, this rule's fix would've added `private` instead.

IMO there is nothing wrong with this rule. But your point is valid, so another rule can be added to the security plugin (something like `security/enforce-private-visibility-if-not-specified`). I'll discuss this with more people.

**Comment by duaraghav8** [comment]
There's no need to make any changes at this point, I'm happy to re-open it in future if a use case emerges. Closing issue for now.
