### ISSUE TITLE
Support for Solidity 0.5.x

### ISSUE THREAD

**Issue by nventuro** [duaraghav8/Ethlint#246]
The 0.5.x family of versions adds a couple new keywords (e.g. addresses can now be `payable`, the location of certain parameters must now be explicitly `calldata`, etc.), which Solium isn't able to parse. Are there plans to support these?

**Comment by elenadimitrova** [comment]
Meanwhile, anyone knows how to switch off the syntax errors this produces without turning off `solium`, completely?

**Comment by duaraghav8** [comment]
@nventuro Sorry for the late response. Yes, the plan is to fully support 0.5 by Jan first week. I haven't been able to work on this issue yet.

@elenadimitrova You can't turn off syntax errors. The easiest way is to add those solidity files to `soliumignore`.
But if you're still convinced that having the ability to turn off compile errors is needed, can you tell me your use case?

**Comment by duaraghav8** [comment]
solved in `v1.2.0`

This linter is now being published simultaneously to npm packages `solium` and `ethlint`. Although not mandatory, I highly recommend that you move to `ethlint`.

See [changelog](https://github.com/duaraghav8/Ethlint/blob/master/CHANGELOG.md#120-2018-12-25-santa)
Please let me know in case any of the 0.5 features are still causing trouble.

**Comment by elopio** [comment]
Thanks @duaraghav8 !
