### ISSUE TITLE
rule for trailing whitespace

### ISSUE THREAD

**Issue by KaiRo-at** [duaraghav8/Ethlint#259]
**Name**
This could either be part of the whitespace rule or be a separate trailing-whitespace one.

**Problem**
Trailing whitespace (spaces or tabs) in a line are just unneeded, wasted bytes and often hard to catch in editors.

**Description**
When applying a fix, trailing whitespace should just be deleted.

**Priority**
This is `Low` but it would be a really nice addition.

**Comment by duaraghav8** [comment]
Agreed, I personally get bothered a lot by trailing whitespaces.
This check will be added in the `whitespace` rule and will supply the `fix` capability.

**Comment by duaraghav8** [comment]
Released in `v1.2.4`
https://github.com/duaraghav8/Ethlint/blob/master/CHANGELOG.md#124-2019-04-08
