### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by ottodevs** [duaraghav8/Ethlint#267]
The project didn't receive any update for a while, and there are several pending PRs and issues without answers...

My question is: Is the project still alive? Are you @duaraghav8 open for any kind of collaboration? I see the docs need some attention, the are confusing parts mixing solium and ethlint instructions, that is happening in the latest docs version.

**Comment by ottodevs** [comment]
Ok I see you are active on the issues, sorry for my wrong perception, the project is great and useful!

**Comment by duaraghav8** [comment]
@ottodevs please do point out what parts of the docs are confusing for you

So far, I've only changed the name of the project from Solium to Ethlint itself (this was due to trademark issues)

Everything else (the CLI & doc references) still contains `solium`.

**Comment by duaraghav8** [comment]
and yes - always open for collaboration!
